services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Lon19ska83
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
